version: "3.9"
services:
    admin:
      build:
        context: ./admin
        dockerfile: Dockerfile
      container_name: admin
      ports:
        - "3000:5173"
      env_file:
        - ./admin/.env


    client:
      build:
        context: ./client
        dockerfile: Dockerfile
      container_name: client
      ports:
        - "4000:5173"
      env_file:
        - ./client/.env
    


    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: backend
      ports:
        - "7000:3000"
      env_file:
        - ./backend/.env
      depends_on:
        - mongo
    

    mongo:
      image: mongo:6
      container_name: mongo
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
        MONGO_INITDB_DATABASE: e-commerce-b-16
      volumes:
        - mongo_data:/data/db

volumes:
  mongo_data:
