name: Deploy Mernstack App

on:
  push:
    branches: [ main ]

jobs:
  changes:
    name: Detect Changed Folders
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.filter.outputs.client }}
      admin: ${{ steps.filter.outputs.admin }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v3

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            client:
              - 'client/**'
            admin:
              - 'admin/**'
            backend:
              - 'backend/**'

      # Debug: print detected outputs
      - name: Debug changed folders
        run: |
          echo "Client changed? ${{ steps.filter.outputs.client }}"
          echo "Admin changed? ${{ steps.filter.outputs.admin }}"
          echo "Backend changed? ${{ steps.filter.outputs.backend }}"

  client:
    name: Deploy Client to Netlify
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.client == 'true'
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Client
        run: npm run build

      - name: Deploy to Netlify (Client)
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./client/dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy Client from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.CLIENT_SITE_ID }}

  admin:
    name: Deploy Admin to Netlify
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.admin == 'true'
    defaults:
      run:
        working-directory: ./admin
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Admin
        run: npm run build

      - name: Deploy to Netlify (Admin)
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./admin/dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy Admin from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.ADMIN_SITE_ID }}

  backend:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    steps:
      - name: Deploy to Render
        uses: render-oss/deploy-action@v1
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
